### ISSUE TITLE
total count of rides for station- Drake Park

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#10]
'/rides/drake_park-station/total_count/'

'I would like a total count of rides by station(Drake Park), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		Drake Park-Station:

	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.31667 AND -121.31603
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.058705 AND 44.059165);

Range:
Lat:  44.058705 | 44.059165
Lon:  -121.31667 | -121.31603

{"station": "drake_park", "total_count" : "#OfTotalCount"}

**Comment by ybakos** [comment]
See #4.
