### ISSUE TITLE
total count of rides for station- G5

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#11]
'/rides/g5-station/total_count/'

'I would like a total count of rides by station(G5), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		G5-Station:

	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.31425 AND -121.31361
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.05733 AND 44.05779);

Range:
Lat:  44.05733 | 44.05779
Lon:  -121.31425 | -121.31361

{"station": "g5", "total_count" : "#OfTotalCount"}

**Comment by ybakos** [comment]
See #4.
