### ISSUE TITLE
count of rides per month per station

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#12]
'/rides/count/:station/per_month'

'I would like a list of the total number of rides per month per station since Zagster began in Bend (2016). Similar request as Logan's.'

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}], {"2017":[{"1":#Jan},Etc...]

**Comment by ybakos** [comment]
References #13 #14 #15 #16 #17 #18 #19

**Comment by ybakos** [comment]
@FelipeCArreola This one is done now.
