### ISSUE TITLE
count of rides per MONTH for station- 10 Barrel Brew Co.

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#13]
'/rides/10_barrel_brew_co-station/count/by_month'

'I would like a list of the total number of rides per month for station "10 Barrel Brew Co." since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.060185 | 44.060645
Lon:  -121.313305 | -121.312665

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
