### ISSUE TITLE
count of rides per MONTH for station- Old Mill

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#14]
'/rides/old_mill-station/count/by_month'

'I would like a list of the total number of rides per month for station "Old Mill" since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.04351 | 44.04397
Lon:  -121.316145 | -121.315505

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
