### ISSUE TITLE
count of rides per MONTH for station- OSU-Cascades

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#15]
'/rides/osu_cascades-station/count/by_month'

'I would like a list of the total number of rides per month for station "OSU-Cascades" since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.04276 | 44.04322
Lon:  -121.333995 | -121.333355

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
