### ISSUE TITLE
count of rides per MONTH for station- Graduate and Research Center (GRC)

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#16]
'/rides/grc-station/count/by_month'

'I would like a list of the total number of rides per month for station "Graduate and Research Center (GRC)" since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.04412 | 44.04458
Lon:  -121.324075 | -121.323435

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
