### ISSUE TITLE
count of rides per MONTH for station- Columbia/Simpson Parking Lot

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#17]
'/rides/columbia_simpson_pl-station/count/by_month'

'I would like a list of the total number of rides per month for station "Columbia/Simpson Parking Lot" since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.048745 | 44.049205
Lon:  -121.32598 | -121.32534

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
