### ISSUE TITLE
count of rides per MONTH for station- Drake Park

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#18]
'/rides/drake_park-station/count/by_month'

'I would like a list of the total number of rides per month for station "Drake Park" since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.058705 | 44.059165
Lon:  -121.31667 | -121.31603

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
