### ISSUE TITLE
count of rides per MONTH for station- G5

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#19]
'/rides/g5-station/count/by_month'

'I would like a list of the total number of rides per month for station "G5" since Zagster began in Bend (2016). Similar request as Logan's.'

Range:
Lat:  44.05733 | 44.05779
Lon:  -121.31425 | -121.31361

{"2016":[{"9":#Sept},{"10":#Oct},{"11":#Nov},{"12":#Dec}],"2017":[{"1":#Jan},Etc.

**Comment by ybakos** [comment]
See #12.
