### ISSUE TITLE
count of rides per DAY for station- Old Mill

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#22]
'/rides/old_mill-station/count/by_day'

'I would like a list of the total number of rides per day for station "Old Mill" since Zagster began in Bend (2016).'

Range:
Lat:  44.04351 | 44.04397
Lon:  -121.316145 | -121.315505

{"2016":[[{"9":[{"16":#day-count"},{"17":"#day-count"},...{"last_day_of_month":"#day-count"}]],...[{"12":[{"1":"#day-count"},...{"last_day_of_month":"#day-count"}]]], {"2017":[[{"1":[{"1":"#day-count"},...}]],...[{"12":[{"1":"#day-count"},...}]]], {"2018":[[{"1":[{"1":"#day-count"},...}]],...[{"current_month_of_data":[{"1":"#day-count"},...{"current_day_of_data":"#day-count"}]]]

**Comment by ybakos** [comment]
See #20.
