### ISSUE TITLE
count of rides per DAY for station- OSU-Cascades

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#23]
'/rides/osu_cascades-station/count/by_day'

'I would like a list of the total number of rides per day for station "OSU-Cascades" since Zagster began in Bend (2016).'

Range:
Lat:  44.04276 | 44.04322
Lon:  -121.333995 | -121.333355

{"2016":[[{"9":[{"16":#day-count"},{"17":"#day-count"},...{"last_day_of_month":"#day-count"}]],...[{"12":[{"1":"#day-count"},...{"last_day_of_month":"#day-count"}]]], {"2017":[[{"1":[{"1":"#day-count"},...}]],...[{"12":[{"1":"#day-count"},...}]]], {"2018":[[{"1":[{"1":"#day-count"},...}]],...[{"current_month_of_data":[{"1":"#day-count"},...{"current_day_of_data":"#day-count"}]]]

**Comment by ybakos** [comment]
See #20.
