### ISSUE TITLE
count of rides per DAY for station- Graduation and Research Center (GRC)

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#24]
'/rides/grc-station/count/by_day'

'I would like a list of the total number of rides per day for station "Graduation and Research Center (GRC)" since Zagster began in Bend (2016).'

Range:
Lat:  44.04412 | 44.04458
Lon:  -121.324075 | -121.323435

{"2016":[[{"9":[{"16":#day-count"},{"17":"#day-count"},...{"last_day_of_month":"#day-count"}]],...[{"12":[{"1":"#day-count"},...{"last_day_of_month":"#day-count"}]]], {"2017":[[{"1":[{"1":"#day-count"},...}]],...[{"12":[{"1":"#day-count"},...}]]], {"2018":[[{"1":[{"1":"#day-count"},...}]],...[{"current_month_of_data":[{"1":"#day-count"},...{"current_day_of_data":"#day-count"}]]]

**Comment by ybakos** [comment]
See #20.
