### ISSUE TITLE
count of rides per DAY for station- G5

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#27]
'/rides/g5-station/count/by_day'

'I would like a list of the total number of rides per day for station "G5" since Zagster began in Bend (2016).'

Range:
Lat:  44.05733 | 44.05779
Lon:  -121.31425 | -121.31361

{"2016":[[{"9":[{"16":#day-count"},{"17":"#day-count"},...{"last_day_of_month":"#day-count"}]],...[{"12":[{"1":"#day-count"},...{"last_day_of_month":"#day-count"}]]], {"2017":[[{"1":[{"1":"#day-count"},...}]],...[{"12":[{"1":"#day-count"},...}]]], {"2018":[[{"1":[{"1":"#day-count"},...}]],...[{"current_month_of_data":[{"1":"#day-count"},...{"current_day_of_data":"#day-count"}]]]

**Comment by ybakos** [comment]
See #20.
