### ISSUE TITLE
/rides/count/per_week/per_membership_type

### ISSUE THREAD

**Issue by DandyAndy22** [osu-cascades/cs160-zagster-service#28]
/rides/count/per_week/per_membership_type

I would like a list of rides per membership type per week at each location.

//per station//
wk 1: {('annual': '20'), ('student-annual': '15'), ('monthly': '10'), ('hourly': '5')}
wk 2: {('annual': '30'), ('student-annual': '25'), ('monthly': '20'), ('hourly': '15')}
etc.
Alternatives considered:

/rides/count/per_month/per_membership_type 
Would also work, but I would like a larger data set.

**Comment by ybakos** [comment]
@DandyAndy22 This one is up, eg: https://zagster-service.herokuapp.com/rides/count/g5/per_week/memberships .

See the [README](https://github.com/osu-cascades/cs160-zagster-service) for info on the `/rides/count/:station/per_week/memberships` route.
