### ISSUE TITLE
Overall Trend of Zagster Usage Since Started in Bend

### ISSUE THREAD

**Issue by loganbertram93** [osu-cascades/cs160-zagster-service#3]
'/rides/PerMonth'

'I would like a list of the total number of rides per month since Gagster began in Bend in 2016.'

{'Sept 16': 'NumberOfRides'} {'Oct 16': 'NumberOfRides'} {'Nov 16': 'NumberOfRides'} etc.

**Comment by ybakos** [comment]
@loganbertram93 Got it. Stay tuned.
