### ISSUE TITLE
/rides/count/per_month/per_membership_type

### ISSUE THREAD

**Issue by KristenOrue** [osu-cascades/cs160-zagster-service#31]
/rides/count/per_month/per_membership_type

I would like a list of rides count per month separated by membership type. 
Ex:
January (1): {('annual':'20'),('student-annual':'15'),('monthly':'10'),('hourly':'5')}
Feburary(2): {('annual':'10'),('student-annual':'8'),(monthly':'6'),(hourly':'4')}
March(3): {('annual':'9'),('student-annual':'7'),(monthly':'5'),(hourly':'3')}

I considered /rides/count/per_membership_type/per_month
Which would look like...
Annual: {('1':'20),('2':'10'),('3':'9')}...
Student-Annual: {('1':'15'),('2':'8'),('3':'7')}...
Monthly: {('1':'10'),{('2':'6'),('3':'5')}...
Hourly: {('1':'5'),('2':'4'),('3':'3')}...

It would work but I think that separating the data by month as the "y" value and membership type as the "x" value matches my sketch for this data visualization and is easier for me to read. I know that both will get me the information I need but I'm trying to make it visually easiest for me to read it, I'm still unsure if my original format will work for I want it to do but

**Comment by ybakos** [comment]
@KristenOrue This one is up (eg: https://zagster-service.herokuapp.com/rides/count/g5/per_month/memberships). Description listed in the [README](https://github.com/osu-cascades/cs160-zagster-service).
