### ISSUE TITLE
bikes taken and returned at differnet stations

### ISSUE THREAD

**Issue by marshjam01** [osu-cascades/cs160-zagster-service#32]
## Be sure to review the paths and results in the [README](https://github.com/ybakos/cs160-zagster-service).

**Is your request path not listed in the [README](https://github.com/ybakos/cs160-zagster-service)? If not, please describe it. Example: `/memberships/foo`:**

**What data do you need to retrieve?**
A clear and concise description of what data you need. For example, "I would like a list of all the membership types."

**Describe the JSON response you'd like**
A clear and concise example of the format of the data returned in the response. For example:
```
{ 'membership': 'foo' } 
```

**Describe alternative request paths you've considered**
A clear and concise description of any existing request paths and JSON responses that are similar to what you need.

**Comment by ybakos** [comment]
@marshjam01 Can you revise this? You need to edit the template. Thanks!
