### ISSUE TITLE
Total count for routes used- from station to station. 

### ISSUE THREAD

**Issue by lauryngomez** [osu-cascades/cs160-zagster-service#33]
'/rides/count/:route_station_to_station'

I would like a list of each route used by looking at the starting and ending stations since Zagster opened in 2016. For example a count of rides from 'grc' to 'osu_cascades' and a separate count for 'grc' to 'ten_barrel' and so on. I would also like a list of counts for the rides that started and ended at the same station. For example, started at 'columbia_simpson' and ended at 'columbia_simpson'.

{ 'count': 'route_station_to_station' }
for example
{23: 'grc' to 'ten_barrel'}
{127: 'grc' to 'osu_cascades'}
...
{500: 'columbia_simpson' to 'columbia_simpson'}
...

The request titled 'total count of rides for station' put in by Felipe is similar to the request that I am putting in. However, I am not interested solely in the count of the starting points, I am interested in the routes taken from station to station. I could have put in an issue for the ending points of each ride, however I thought it would make it easier on me to have that put into this issue, as well.

**Comment by ybakos** [comment]
@lauryngomez Thanks for the data request! This is a good one - and a bit tricky. It'll take some time but we'll get it up asap.

**Comment by ybakos** [comment]
@lauryngomez This is now online for you. But for now, it will only return the count of rides from one specific origin and destination. Note the path:

`/rides/count/from/:start/to/:end`

Where `:start` is a valid station name and `:end` is also a valid station name. This allows you to obtain any of the counts directly, one at a time. (If you want to grab all the counts together, please let me know.)
