### ISSUE TITLE
/rides/count/per_season

### ISSUE THREAD

**Issue by BrennenKarp** [osu-cascades/cs160-zagster-service#34]
I would like the amount of rides per month. 
{'month': 'number of rides'}
Some that are similar are the number of rides per month however that doesn't give me specific enough data.

**Comment by ybakos** [comment]
@BrennenKarp Thanks for the data request! We've got an endpoint that returns the number of rides per month. (Addressed in #3 ).

See the README and look for `/rides/count/per_month`.
