### ISSUE TITLE
I would like to get the total number of rides per year.

### ISSUE THREAD

**Issue by etmotox** [osu-cascades/cs160-zagster-service#35]
'/rides/count/per_year'

I would like a list of all the rides per year.
Something like this:
{ '2016': '1500' }, { '2017': '6800' }, { '2018': '10500' }

I have considered the following. I think it is very similar, but wont provide accurate numbers. I will be using rides per month, and rides per year.
'rides/count/per_month'

{ 'January': '1100' }, { 'February': '900' }, { 'March': '1800' }...

**Comment by ybakos** [comment]
@etmotox Thanks for the data request! 

Rides per year is done now - see the README. `/rides/count/per_year`.

For `/rides/count/per_month`, this was addressed in https://github.com/osu-cascades/cs160-zagster-service/issues/3.

See the README for `/rides/count/per_month`. They are segmented by years, and then the months within each year.

**Comment by etmotox** [comment]
Thank you!
