### ISSUE TITLE
total count of rides for station- Galveston

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#4]
'/rides/galveston-station/total_count/'

'I would like a total count of rides by station(Galveston), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		Galveston-Station:

	SELECT COUNT(*)
		FROM `rides`
    		WHERE `start_lon` BETWEEN -121.328415 AND -121.327775
        		IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.056495 AND 44.056955)

Range:
Lat:  44.056495 | 44.056955
Lon:  -121.328415 | -121.327775

{"station": "galveston", "total_count" : '#OfTotalCount'}

**Comment by ybakos** [comment]
@FelipeCArreola I'll close the other issues and just use this one. Thanks for sifting through lat and lons!

References #5 #6 #7 #8 #9 #10 #11 .

**Comment by ybakos** [comment]
@FelipeCArreola This is going to just return the number of rides per station based on `start_lat` and `start_lon` unless you say otherwise.

**Comment by ybakos** [comment]
@FelipeCArreola This one's up. See the [README](https://github.com/osu-cascades/cs160-zagster-service/blob/master/README.md). Note that I changed the path to:

`/rides/count/:station_name`

And the response will just be: `{"count":"num"}` for that particular station.
