### ISSUE TITLE
Coordinates and date of rides

### ISSUE THREAD

**Issue by Colin-Suckow** [osu-cascades/cs160-zagster-service#41]
/rides/location

I would like a list of every rides' id, start lat, start lon, end lat, end lon, and the start and end times of those rides.

{"id":1,"start_lat":44.05893741,"start_lon":-121.3163919,"end_lat":44.06258668,"end_lon":-121.315942,"start_time":"2018-09-14T14:29:00.000Z","end_time":"2018-09-15T10:23:00.000Z"}

/rides/example has the data I need in it, however it returns more columns than necessary, and it obviously only returns one row.

**Comment by ybakos** [comment]
@Colin-Suckow This one is ready for you, but the path is /rides/locations_and_times. eg:

https://zagster-service.herokuapp.com/rides/locations_and_times

Note that this is a lot of data, and may take some time to receive it all once you place the request from your JS. (It's a great opportunity to learn about how the `getJSON` method is asynchronous, and why, when we call it, we pass a path and the name of a function to execute once the response is received. (Ask me if you don't know about this stuff.)
