### ISSUE TITLE
total count of rides for station- 10 Barrel Crew Co.

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#5]
'/rides/10_barrel_brew_co-station/total_count/'

'I would like a total count of rides by station(10 Barrel Brew Co.), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		10 Barrel Brew Co.-Station:
	
	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.313305 AND -121.312665 
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.060185 AND 44.060645);

Range:
Lat:  44.060185 | 44.060645
Lon:  -121.313305 | -121.312665

{"station": "10_barrel_brew_co", "total_count" : '#OfTotalCount'}

**Comment by ybakos** [comment]
See #4.
