### ISSUE TITLE
total count of rides for station- Old Mill

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#6]
'/rides/old_mill-station/total_count/'

'I would like a total count of rides by station(Old Mill), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		Old Mill-Station:
		

	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.316145 AND -121.315505 
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.04351 AND 44.04397);

Range:
Lat:  44.04351 | 44.04397
Lon:  -121.316145 | -121.315505

{"station": "old_mill", "total_count" : '#OfTotalCount'}

**Comment by ybakos** [comment]
See #4.
