### ISSUE TITLE
total count of rides for station- OSU-Cascades

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#7]
'/rides/osu_cascades-station/total_count/'

'I would like a total count of rides by station(OSU-Cascades), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		OSU-Cascades-Station:
			
	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.333995 AND -121.333355
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.04276 AND 44.04322);

Range:
Lat:  44.04276 | 44.04322
Lon:  -121.333995 | -121.333355

{"station": "osu_cascades", "total_count" : '#OfTotalCount'}

**Comment by ybakos** [comment]
See #4.
