### ISSUE TITLE
total count of rides for station- Graduate and Research Center (GRC)

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#8]
'/rides/grc-station/total_count/'

'I would like a total count of rides by station[Graduate and Research Center (GRC)], since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		GRC-Station:

	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.324075 AND -121.323435 
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.04412 AND 44.04458);

Range:
Lat:  44.04412 | 44.04458
Lon:  -121.324075 | -121.323435

{"station": "grc", "total_count" : '#OfTotalCount'}

**Comment by ybakos** [comment]
See #4.
