### ISSUE TITLE
total count of rides for station- Columbia/Simpson Parking Lot

### ISSUE THREAD

**Issue by FelipeCArreola** [osu-cascades/cs160-zagster-service#9]
'/rides/columbia_simpson_pl-station/total_count/'

'I would like a total count of rides by station(Columbia/Simpson Parking Lot), since Zagster Bike Share began in Bend starting in 2016.'

	Attempted at clustering data.
		Columbia/Simpson Parking Lot-Station:

	SELECT COUNT(*)
		FROM `rides`
    			WHERE `start_lon` BETWEEN -121.32598 AND -121.32534 
        			IN
				(SELECT *
					FROM `rides`
						WHERE `start_time` IS NOT NULL AND `end_time` IS NOT NULL 
							AND `start_lat` IS NOT NULL AND `start_lon` IS NOT NULL 
							AND `end_lat` IS NOT NULL AND `end_lon` IS NOT NULL 
							AND `start_lat` BETWEEN 44.048745 AND 44.049205);

Range:
Lat:  44.048745 | 44.049205
Lon:  -121.32598 | -121.32534

{"station": "columbia_simpson_pl", "total_count" : '#OfTotalCount'}

**Comment by ybakos** [comment]
See #4.
